name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp'
runs:
  using: 'docker'
  image: 'docker://curvhealth/action-slack-notify:v2.1.1'
branding:
  icon: 'bell'
  color: 'yellow'
